### ISSUE TITLE
Problem with generate-dataset.py

### ISSUE THREAD

**Issue by temptitle** [ecaradec/humble-yolo#1]
python3 generate-dataset.py
Traceback (most recent call last):
  File "generate-dataset.py", line 22, in <module>
    with open('Labels/%d.txt' % j,'w+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Labels/0.txt'

**Comment by ksloke** [comment]
remove the slash e.g. 'Labels%d.txt' 
do the same on line 48

**Comment by Moondra** [comment]
You need to create a LABELS folder as well as Image folder.

**Comment by ecaradec** [comment]
Yes, you should create folders.
