### ISSUE TITLE
What is the YOLO performance ?

### ISSUE THREAD

**Issue by OscarFraustoPerez** [ecaradec/humble-yolo#17]
Hi, What is the YOLO performance that you got ?  (Accuracy, etc)

**Comment by ecaradec** [comment]
I don't remember, and I don't think that I really paid attention to it. There should probably be two different accuracy because you need one for the box precision and one for the class categorisation accuracy.

**Comment by OscarFraustoPerez** [comment]
Did you get the mAP ?

**Comment by ecaradec** [comment]
Interesting. I din't knew that measure. I'll have a read. So no I don't have it.
