### ISSUE TITLE
Mistake in class loss?

### ISSUE THREAD

**Issue by off99555** [ecaradec/humble-yolo#6]
I think that you computed the class loss wrongly. The index should go from 0 to 3, not 0 to 2. Because you have 3 classes in your dataset.
https://github.com/ecaradec/humble-yolo/blob/07048325cf8af06b743e71a2d880093f44fe14bc/main.py#L104-L105

The above code will not be a mistake if you purposely decided to not compute the class loss for "none" class. But I think that kind of behavior does not make sense when you use sigmoid activation. If you use softmax activation then the "none" class will have high probability when the other 2 classes have low probabilities.

**Comment by ecaradec** [comment]
I agree that it's not really clean, but that's what I actually wanted. YOLO doesn't predict a class for None, instead it trains the probability of all the field of the one hot encoded vector class to 0, if I remember right. This is why I'm not using softmax activation (but it may totally not be the best design here ).

**Comment by off99555** [comment]
I've tried implementing the yolo loss from scratch and it doesn't seem like this class prediction is important. So it depends on your choice.
